### PR TITLE
Replace external images with TikZ images.

### PR DESCRIPTION
**Pull request by peanutbutterandcrackers**
- Trees have been replaced to be 'native' TikZ images.
- Bunch of .svg and .png files have been deleted.
- Associated changes have been made to the Makefile, etc.
- Containerfile has been updated to explicitly use debian:bookworm.

Sample:
image
image

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
Some Graphs:
image

image

**Comment by peanutbutterandcrackers** [comment]
Correction.

From
image
to
image

**Comment by peanutbutterandcrackers** [comment]
DFT:
image

**Comment by peanutbutterandcrackers** [comment]
All images have now been converted to TikZ format.

[brisk.pdf](https://github.com/divilian/cool-brisk-walk/files/11991017/brisk.pdf)

**Comment by divilian** [comment]
Wow, @peanutbutterandcrackers, you put a lot of time into this, and I agree that most of the drawings are noticeably improved. Thanks! (Dijkstra's and Prim's diagrams in particular are waaaaay better!)

- Figs 5.4 and 5.5 probably consumes too much horizontal space right now for the printers to be happy. Either you or I can play with shrinking them and hopefully retaining legibility. (probably also 5.26 through 5.29)
- Nitpick: I think 5.30 would be prettier if all the nodes were the same size, even though their names are not the same length.
- Fig 5.8 is on a page by itself which looks icky to me, but I can play around with pagination when you've checked in the rest of these items.
- The unlabeled nodes in Figures 5.21, 5.22, 5.23 are smaller than the others, which looks a bit jarring. Maybe you intended this so that they'd stick out. I'd recommend giving them a character -- perhaps asterisk "*" -- and then in the text swap "...if we added the three blank nodes..." to "...if we added the three starred nodes...".
- The round corners on the "BRISK" permutations on pp.152-153 look a little weird. I don't suppose there's an easy fix for this?

**Comment by peanutbutterandcrackers** [comment]
@divilian - Could you please check the changes https://github.com/peanutbutterandcrackers/cool-brisk-walk/pull/1 and see if you are happy with them? I will merge that into this branch if you are.

> The round corners on the "BRISK" permutations on pp.152-153 look a little weird. I don't suppose there's an easy fix for this?

This wasn't a change that I introduced, and it always seems to have been that way, but I will take a stab at it anyways and submit it as a separate PR (if I can come up with something).

**Comment by peanutbutterandcrackers** [comment]
Superseded by https://github.com/divilian/cool-brisk-walk/pull/25

**Pull request closed without merging**
